[package]
name = "rattler-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
axum = {version="0.6.6", features=["json"]}
serde = {version="1.0.152", features=["derive"]}
serde_json = "1.0.68"
tokio = {version="1.25.0", features=["full"]}
rattler_solve = {path="../rattler/crates/rattler_solve"}
rattler_conda_types = {path="../rattler/crates/rattler_conda_types"}
rattler_repodata_gateway = {path="../rattler/crates/rattler_repodata_gateway"}
futures = "0.3.26"
reqwest = "0.11.14"
