[package]
name = "rattler-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
axum = {version="0.6.6", features=["json"]}
serde = {version="1.0.152", features=["derive"]}
serde_json = "1.0.68"
tokio = {version="1.25.0", features=["full"]}
rattler_solve = {git="https://github.com/aochagavia/rattler.git", branch="libsolv-reuse-input"}
rattler_conda_types = {git="https://github.com/aochagavia/rattler.git", branch="libsolv-reuse-input"}
rattler_repodata_gateway = {git="https://github.com/aochagavia/rattler.git", branch="libsolv-reuse-input"}
futures = "0.3.26"
reqwest = "0.11.14"
dashmap = "5.4.0"
tokio-util = {version="0.7.7", features=["io"]}
async-compression = {version="0.3.15", features=["tokio", "bzip2", "zstd"]}
thiserror = "1.0.39"
tracing = "0.1.37"
tracing-subscriber = {version="0.3.16", features=["env-filter"]}

[dev-dependencies]
mock_instant = "0.2.1"
