[package]
name = "rattler-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
axum = {version="0.6.6", features=["json"]}
serde = {version="1.0.152", features=["derive"]}
serde_json = "1.0.68"
tokio = {version="1.25.0", features=["full"]}
rattler_solve = {git="https://github.com/aochagavia/rattler.git", branch="libsolv-installed-packages"}
rattler_conda_types = {git="https://github.com/aochagavia/rattler.git", branch="libsolv-installed-packages"}
