on:
  release:
    types: [ created ]
  push:

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      matrix:
        platform:
          - release_for: linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: rattler-server
            name: rattler-server-linux-x86_64-musl.tar.gz

          - release_for: linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: rattler-server
            name: rattler-server-linux-aarch64-musl.tar.gz

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: rattler-server
            name: rattler-server-darwin-x86_64.tar.gz

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: rattler-server
            name: rattler-server-darwin-aarch64.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          cd -
      - name: Generate SHA-256
        if: matrix.platform.os == 'macOS-latest'
        run: shasum -a 256 ${{ matrix.platform.name }}
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "rattler-server-*"
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'release'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name != 'release'
        with:
          name: Binary
          path: |
            rattler-server-*
